server:
  AppVersion: 1.0.0
  Port: :9090
  Mode: Development
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

postgres:
  PostgresqlHost: postgres
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgrespw
  PostgresqlDbname: mdb
  PostgresqlSslmode: false
  PgDriver: pgx

keycloak:
  EndPoint: http://keycloak:8080
  ClientId: mdb-client
  ClientSecret: D0x5ScPy7dr4fWD04CuMB7pP7BBh7Qxk
  Realm: mdb