environment: local
server:
  AppVersion: 1.0.0
  Port: :9090
  Mode: Development
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

postgres:
  PostgresqlHost: postgres
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgrespw
  PostgresqlDbname: mdb
  PostgresqlSslmode: false
  PgDriver: pgx

keycloak:
  EndPoint: http://keycloak:8080
  ClientId: mdb-client
  ClientSecret: D0x5ScPy7dr4fWD04CuMB7pP7BBh7Qxk
  Realm: mdb

cloudinary:
  CloudName: dln5uctjy
  ApiKey:
  ApiSecret:
  FolderPath: shiftflix

tmdb:
  Url: https://api.themoviedb.org/3
  ApiKey:

stripe:
  PublishableKey: pk_test_51NEEYoCBUAGsQ2OtKbGkg8qKTroDdItzsT8MBx2N89GwUqFjftSbP40oiFPHokUHF6tlC4vXYaYBSuY1u7mwfzf000ngRHmlmq
  SecretKey:

mail:
  Host: mailhog
  Port: 1025
  From: system@shiftflix.com